# A versão especificada do docker compose não é mais obrigatória
# version: '3.8'

services:
  app:
    # Contrói a imagem a partir do Dockerfile na raiz do projeto
    build: .
    # Se não colocar um name, criará um nome random
    container_name: imersao-devops
    ports:
      # Mapeia a porta 8000 do host para a porta 8000 do container
      - "8000:8000"
    volumes:
      # Montao diretório atual, onde está seu código, em /app do container.
      # Para desenvolvimento, a linha abaixo reflete as mudanças no código sem precisar reconstruir a imagem devido --reload do uvicorn.
      - .:/app
